### ISSUE TITLE
希望能支持使用独立的Axios实例和插入Interceptors

### ISSUE THREAD

**Issue by pboymt** [nullcc/ts-retrofit#1]
RT，我已经Fork了代码添加功能了，这两天我把PR提交一下。

**Comment by nullcc** [comment]
Hi @pboymt 感谢对这个项目的关注，欢迎PR

**Comment by pboymt** [comment]
@nullcc  已经通过 #2 PR了

**Comment by softboy99** [comment]
setStandalone(true) 是单例还是传入axios是单例？

**Comment by pboymt** [comment]
setStandalone是生成一个单例的

发自我的iPad

**Comment by softboy99** [comment]
setStandalone(true)是单例，对吗？
