### ISSUE TITLE
Multipart

### ISSUE THREAD

**Issue by remalkoil** [nullcc/ts-retrofit#15]
Hello, 
I've the following api service's method:
```typescript
@POST('/my-custom-url')
@Multipart
async uploadFileFromBrowser(@Part('file') file: PartDescriptor<File>): Promise<Response<any>> {
   return {} as Response;
}
```
I'm calling it (from an Angular project) with the following code:
```typescript
async uploadAction() {
  const fileInput = document.getElementById('file') as HTMLInputElement;
  const files = fileInput.files;
  const file = files[0];
  const response = await this.api.uploadFileFromBrowser({value: file, filename: file.name});
}
```

inside baseService.ts, method `_resolveParameters`, current line 117:
 ```typescript
headers = {...headers, ...(data as FormData).getHeaders()};
```
`data` doesn't have `getHeaders` method; Maybe 'cause i'm from a browser and not from node?

I've solved with this code (baseService.ts, method `_resolveParameters`, line ~116):
```typescript
    if (headers["content-type"] && headers["content-type"].indexOf("multipart/form-data") !== -1) {
      const formData = data as FormData;
      if (formData?.getHeaders != null) {
        headers = {...headers, ...formData.getHeaders()};
      }
    }
```

Best regards,
Daniele

**Comment by nullcc** [comment]
Hello Daniele @remalkoil, thank you for your feedback.
Yes, you are right, it's a bug. I found that https://github.com/form-data/form-data#axios mentions we only need to call `form.getHeaders();` for multipart content type in node. 
I created a PR to fix this bug: https://github.com/nullcc/ts-retrofit/pull/16
ts-retrofit v1.11.1 fixed this bug, it has been released.

Best regards,
Ethan
