### ISSUE TITLE
Proposition - helper function STUB_RESPONSE to automatically case empty object to Response

### ISSUE THREAD

**Issue by npwork** [nullcc/ts-retrofit#19]
It's already implemented in my PR #18
**Problem:**
Example:
```typescript
@BasePath(API_PREFIX)
export class InterceptorService extends BaseService {
  @GET("/interceptor")
  async getParams(): Promise<Response> { return <Response>{} };

  @POST("/interceptor")
  async createParams(@Body body: Post): Promise<Response> { return <Response>{} };
}
```

I have to do manually cast an empty object to Response in every method `return <Response>{}`

**Solution:**
Use stub-method to automatically cast empty object to expected type.

```typescript
export const STUB_RESPONSE = <T>() => ({} as T);
```

Code from example will become:
```typescript
@BasePath(API_PREFIX)
export class InterceptorService extends BaseService {
  @GET("/interceptor")
  async getParams(): Promise<Response> { return STUB_RESPONSE() };

  @POST("/interceptor")
  async createParams(@Body body: Post): Promise<Response> { return STUB_RESPONSE() };
}
```

**Comment by softboy99** [comment]
Hi
is it possible without the return statement? you can find it retrofitjs : github.com/itfinally/RetrofitJs
async getParams(): Promise<Response> & void{};

**Comment by npwork** [comment]
> Hi
> is it possible without the return statement? you can find it retrofitjs : github.com/itfinally/RetrofitJs
> async getParams(): Promise & void{};

I made a fork and implemented this feature there
https://github.com/npwork/ts-retrofit2

**Comment by softboy99** [comment]
> > Hi
> > is it possible without the return statement? you can find it retrofitjs : github.com/itfinally/RetrofitJs
> > async getParams(): Promise & void{};
> 
> I made a fork and implemented this feature there
> https://github.com/npwork/ts-retrofit2

Hi,
Thanks, very good. But it is failed compiled in vite. Please add ES6 native module support. Thanks
